arrowParens: "avoid"
bracketSameLine: true
bracketSpacing: true
jsxSingleQuote: true
printWidth: 80
quoteProps: "as-needed"
semi: true
# singleAttributePerLine: true
singleQuote: true
tabWidth: 2
trailingComma: "es5"
useTabs: true