export const searchMockData = {
	pagination: {
		currentPage: 1,
		pageSize: 3,
		totalCount: 11,
	},

	data: [
		{
			id: '1',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
		{
			id: '2',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
		{
			id: '3',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
		{
			id: '4',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
		{
			id: '5',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
		{
			id: '6',
			title: 'title',
			description: 'description',
			departureCity: 'departureCity',
			travelDays: 'travelDays',
			discountPresent: 'discountPresent',
			tripType: 'tripType',
			touristRoutePictures: [
				{ url: 'https://z3.ax1x.com/2020/12/15/rMQOIJ.jpg' },
			],
			price: 'price',
			originalPrice: 'originalPrice',
			rating: 'rating',
		},
	],
};
